name: Build & Deploy to GitHub Pages manually (to can add CNAME)

on:
  push:
    branches:
      - stop_branch # main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install mkdocs
        run: |
          pip install git+https://github.com/thangckt/mkdocs-material.git@master         # tabs_header_v8    master    tabs_header_yinkh
          pip install mkdocstrings[python]>=0.18
          
      - name: Build
        run: mkdocs build --clean
      
      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          
      - name: Create CNAME file
        run: echo "thang.eu.org" > site/CNAME
    
      - name: Add CNAME file to Git index
        run: git --work-tree=site add CNAME
        
      
      - name: Create and push to gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git --work-tree site add --all
          git --work-tree site commit -m "Deploy to GitHub Pages"
          git push origin HEAD:gh-pages --force
