# This is a basic workflow to help you get started with Actions
name: gh-deploy & push-to-another-repo

on:
  push:
    branches:
      -  main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: MkDocs Github Pages automatic deployment
    runs-on: ubuntu-latest   # ubuntu-latest
    steps:
      - name: Checkout main          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies  # mkdocs-jupyter can cause broken in tabs-header
        run: |
          pip install git+https://github.com/thangckt/mkdocs-material.git@master         # tabs_header_v8    master    tabs_header_yinkh
          pip install mkdocstrings[python]>=0.18
          # pip install mkdocs-blogging-plugin==2.2
          # pip install mkdocs-jupyter # conflict
          # pip install mkdocs-enumerate-headings-plugin #  mkdocs

      - name: MkDocs gh-deploy    # This will create `gh-pages` branch contain `mkdocs-site`
        run: mkdocs gh-deploy --force --verbose


      # - name: Push to another repository  # This step to copy a folder and push to another repo
      #   id: push_directory
      #   uses: thangckt/github-action-push-to-another-repository@main    #  cpina/github-action-push-to-another-repository@main   # use workflow `action.yml` in this repo
      #   env:
      #     SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      #   with:
      #     source-directory: './'
      #     destination-github-username: 'thangckt'
      #     destination-repository-name: 'thangckt.github.io'
      #     user-email: thangckt@gmail.com
      #     commit-message: See ORIGIN_COMMIT from $GITHUB_REF
      #     target-branch: gh-pages        # push branch `gh-pages` from `source-repo` to `destination-repo`


